state_machine_node:
  ros__parameters:
    logging:
      lantern_log_path: "lanterns_log.csv"
      event_log_path: "statemachine_events.log"
    topics:
      topic_state: "statemachine/state"
      topic_cmd_: "statemachine/cmd"
      topic_heartbeat: "heartbeat"

      topic_lantern_detections: "detected_lanterns"
      current_state_est: "current_state_est"

      topic_viz_checkpoint: "statemachine/viz/checkpoint"
      topic_viz_path_flight: "statemachine/viz/path_flight"
    time:
      alive_tol_sec: 10.0
      pub_state_loop_sec: 1.0
      boot_timeout_sec: 60.0
    lanterns:
      lantern_merge_dist_m: 0.2
    checkpoints:
      positions:
        [-38.0, 10.0, 15.0,
        -320.0, 8.0, 17.0]
      reach_dist_m: 0.5
    viz:
      path_sample_dist_m: 0.2
    nodes:
      ["planner",
       "sampler",
       "path_planner",
       "controller_node",
       "lantern_detector",
       "octomap_server"]
    node_roles:
      controller_index: 3
      waypoint_index: 0
      planner_index: 2
      lantern_index: 4
    
