state_machine_node:
  ros__parameters:
    logging:
      lantern_log_path: "lanterns_log.csv"
      event_log_path: "statemachine_events.log"
    topics:
      topic_state: "statemachine/state"
      topic_cmd_: "statemachine/cmd"
      topic_heartbeat: "heartbeat"

      topic_lantern_detections: "detected_lanterns"
      current_state_est: "current_state_est"
      topic_octomap: "octomap_binary"

      topic_viz_checkpoint: "statemachine/viz/checkpoint"
      topic_viz_path_flight: "statemachine/viz/path_flight"
    time:
      alive_tol_sec: 10.0
      pub_state_loop_sec: 1.0
      boot_timeout_sec: 60.0
      takeoff_cmd_retry_sec: 1.5
    lanterns:
      lantern_merge_dist_m: 0.2
    checkpoints:
      positions:
        [-320.0, 9.0, 16.0]
      reach_dist_m: 0.5
    landing:
      xy_radius_m: 0.5
      clearance_m: 0.2
      probe_depth_m: 30.0
    viz:
      path_sample_dist_m: 0.2
    nodes:
      ["planner",
       "sampler",
       "path_planner",
       "controller_node",
       "lantern_detector",
       "octomap_server"]
    node_roles:
      controller_index: 3
      waypoint_index: 0
      planner_index: 2
    
