planner:
  ros__parameters:
    max_v: 2.5
    max_a: 1.5

    waypoints: [ #-38.02, 10.0, 8.0,   # only for parameter tuning
                #-38.02, 10.0, 10.0   # only for parameter tuning
                #-50.0, 10.0, 7.0,  
                -100.0, 10.0, 15.0,  # comment out for parameter tuning
                -125.0, 10.0, 19.0,  # comment out for parameter tuning
                -150.0, 10.0, 23.0,  # comment out for parameter tuning
                -200.0, 10.0, 25.0,  # comment out for parameter tuning
                -250.0, 10.0, 19.0,  # comment out for parameter tuning
                -300.0, 10.0, 15.0]  # comment out for parameter tuning
                # -350.0, 7.0, 15.0,   # testing for latern detection
                # -600.0, 7.0, 15.0]   # testing for latern detection
    
    stop_index: -1
