planner:
  ros__parameters:
    max_v: 2.5
    max_a: 1.5

    waypoints: [ -50.0, 10.0, 15.0,
                -100.0, 10.0, 40.0,
                -125.0, 10.0, 35.0,
                -150.0, 10.0, 30.0,
                -200.0, 10.0, 25.0,
                -250.0, 10.0, 20.0,
                -300.0, 10.0, 15.0]
    
    stop_index: 10
