planner:
  ros__parameters:
    max_v: 5.0
    max_a: 2.0

    waypoints: [10.0, 0.0, 3.0,
                22.0, 3.0, 4.0,
                30.0, 10.0, 3.0,
                35.0, 25.0, 13.0,
                35.0, 35.0, 6.0,
                25.0, 39.0, 11.0,
                16.0, 39.0, 11.0,
                8.0, 39.0, 11.0,
                10.0, 0.0, 3.0,
                22.0, 3.0, 4.0,
                30.0, 10.0, 3.0,
                35.0, 25.0, 13.0,
                35.0, 35.0, 6.0,
                25.0, 39.0, 11.0,
                16.0, 39.0, 11.0,
                13.0, 39.0, 11.0,
                8.0, 39.0, 11.0]
    
    stop_index: 15
